FROM nvcr.io/nvidia/l4t-pytorch:r35.4.1-pth2.0-runtime
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements_rag.txt