apiVersion: v1
kind: Service
metadata:
  name: context-admin
  namespace: orange-code
  labels:
    app: context-admin
    component: admin-ui
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: context-admin