apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orange-code
resources:
- namespace.yaml
- persistent-volumes.yaml
- configmap.yaml
- context-service-deployment.yaml
- context-service-service.yaml
- context-admin-deployment.yaml
- context-admin-service.yaml
- agent-config.yaml
- agent-no-rag-deployment.yaml
- agent-no-rag-service.yaml